# Generated by Django 5.2.1 on 2025-05-22 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='producto',
            new_name='product',
        ),
    ]
