# Generated by Django 5.2.1 on 2025-05-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/productos/', verbose_name='foto'),
        ),
    ]
